apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://${PROMETHEUS_HOST}
    isDefault: true
    editable: true
    jsonData:
      timeInterval: '15s'

  - name: Loki
    type: loki
    access: proxy
    url: http://${LOKI_HOST}
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
